version: '3.8'
services:
    redis:
        image: "redis:alpine"
    rabbitmq:
        image: 'rabbitmq:3-management'
        hostname: rabbit
        ports:
          - '5672:5672'
          - '15672:15672'
    articles:
        container_name:
            articles
        build: ./articles/
        volumes:
            - ./articles/:/usr/src/app/
        ports:
            - 5001:5001
        environment:
            PORT: 5001
            FLASK_DEBUG: 1
        links:
            - rabbitmq
            - redis
        depends_on:
            - rabbitmq
    notification:
        container_name:
            notification
        build: ./notification/
        volumes:
            - ./notification/:/usr/src/app/
        ports:
            - 5002:5002
        environment:
            PORT: 5002
            FLASK_DEBUG: 1
        links:
            - rabbitmq
            - redis
        depends_on:
            - rabbitmq
